### ISSUE TITLE
mavimo/drone provider

### ISSUE THREAD

**Issue by mavimo** [jimsheldon/terraform-provider-drone#4]
@jimsheldon I see that you create this new repo, I already have a provider for drone https://registry.terraform.io/providers/mavimo/drone there is something missing that will force you to create a new provider? 

If something is missing what do you think to join our forces? 😄 

PS: if you want to keep your project for some specific reason NP

**Comment by jimsheldon** [comment]
Hello @mavimo, thanks for reaching out.

I created this project after searching for the Terraform registry for "drone", where https://github.com/Lucretius/terraform-provider-drone is the top result. I reached out to the author, he said he is not able to maintain that project, so I decided to try and update it myself.

Unfortunately I did not find your provider, it definitely would have saved me some time!

The provider from Lucretius did not use v2 of the Terraform modules, it also did not support templates or any data sources. I see that your provider uses v2 and supports templates, which is great. Do you have any plans to add data sources? I added a few in this provider, I'd like to add more.

I would certainly like to collaborate, and ideally I'd like there to be an official Drone Terraform provider. Are you confident that you have the bandwidth to continue maintaining your provider?

**Comment by mavimo** [comment]
@jimsheldon yes, I'm going to maintain it for the upcoming months/years (depends on how much changes are in the Drone 
 itself 😅 ) and already start collecting people that will like to contribute (plus some people from some company that re using it)

About the "data sources" sure, if you want I can merge what you already done (adding more if you need) I will really appreciate new contributions 😄

**Comment by mavimo** [comment]
FYI data sources get integrated in the mavimo/drone provider :)
